### ISSUE TITLE
QLoggingCategoryでエラーが出てビルドができません。

### ISSUE THREAD

**Issue by egapageae** [KengoSawa2/RapidCopy#2]
RapidCopy-master/main.cpp:10: エラー: QLoggingCategory: No such file or directory
 #include <QLoggingCategory>
となりビルドができません。
公式サイトからqt-opensource-linux-x64-5.6.2.runをダウンロードしたのですが…

**Comment by egapageae** [comment]
Qtバージョンが5.6.2に指定できていなかったようです。
しかし、以下のようにエラーになりました。

22:42:26: プロジェクト rapidcopy_main のステップを実行中...
22:42:26: 設定が変更されていない為、qmake ステップをスキップします。
22:42:26: 起動中: "/usr/bin/make" 
g++ -c -pipe -std=c++11 -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -D_GNU_SOURCE -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../RapidCopy -I. -I../Qt5.6.2/5.6/gcc_64/include -I../Qt5.6.2/5.6/gcc_64/include/QtWidgets -I../Qt5.6.2/5.6/gcc_64/include/QtMultimedia -I../Qt5.6.2/5.6/gcc_64/include/QtGui -I../Qt5.6.2/5.6/gcc_64/include/QtNetwork -I../Qt5.6.2/5.6/gcc_64/include/QtCore -I. -I. -I../Qt5.6.2/5.6/gcc_64/mkspecs/linux-g++ -o fastcopy.o ../RapidCopy/fastcopy.cpp
../RapidCopy/fastcopy.cpp:2:5: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
     "@(#)Copyright (C) 2004-2012 H.Shirouzu  fastcopy.cpp ver2.10";
     ^
../RapidCopy/fastcopy.cpp: In destructor 'virtual FastCopy::~FastCopy()':
../RapidCopy/fastcopy.cpp:130:15: warning: deleting 'void*' is undefined
     delete [] confirmDst;
               ^
../RapidCopy/fastcopy.cpp:131:15: warning: deleting 'void*' is undefined
     delete [] dst;
               ^
../RapidCopy/fastcopy.cpp:132:15: warning: deleting 'void*' is undefined
     delete [] src;
               ^
../RapidCopy/fastcopy.cpp: At global scope:
../RapidCopy/fastcopy.cpp:294:74: warning: unused parameter 'dst_fstype' [-Wunused-parameter]
 bool FastCopy::IsAclSupport(FastCopy::FsType src_fstype,FastCopy::FsType dst_fstype)
                                                                          ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::InitSrcPath(int)':
../RapidCopy/fastcopy.cpp:547:46: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (GetChar(fname, 0) == '*' || attr == 0xffffffff) {
                                              ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::RegisterInfo(const PathArray*, const PathArray*, FastCopy::Info*, const PathArray*, const PathArray*)':
../RapidCopy/fastcopy.cpp:718:45: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
                 regExp[kind][ftype].Init("*");
                                             ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::AllocBuf()':
../RapidCopy/fastcopy.cpp:892:39: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
        ||(info.flags & SKIP_EMPTYDIR) && !mkdirQueueBuf.Buf() || !dstDirExtBuf.Buf()){
                                       ^
../RapidCopy/fastcopy.cpp: At global scope:
../RapidCopy/fastcopy.cpp:1065:40: warning: unused parameter 'path' [-Wunused-parameter]
 BOOL FastCopy::FilterCheck(const void *path, const void *fname, DWORD attr, _int64 write_time,_int64 file_size,int flags)
                                        ^
../RapidCopy/fastcopy.cpp:1480:103: warning: unused parameter 'stat' [-Wunused-parameter]
 BOOL FastCopy::MakeDigest(void *path, VBuf *vbuf, TDigest *digest, BYTE *val, _int64 *fsize,FileStat *stat)
                                                                                                       ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::ReadProc(int, bool)':
../RapidCopy/fastcopy.cpp:1681:26: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
     if(confirm_dir_local && (isSameDrv ? ReadDstStat() : WaitDstRequest()) == FALSE
                          ^
../RapidCopy/fastcopy.cpp:1742:39: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
             || info.mode == MOVE_MODE && openFilesCnt >= MOVE_OPEN_MAX
                                       ^
../RapidCopy/fastcopy.cpp:1743:25: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
             || waitTick && openFilesCnt >= WAIT_OPEN_MAX
                         ^
../RapidCopy/fastcopy.cpp:1840:28: warning: missing initializer for member 'FastCopy::ReqBuf::req' [-Wmissing-field-initializers]
         ReqBuf req_buf = {0};
                            ^
../RapidCopy/fastcopy.cpp:1840:28: warning: missing initializer for member 'FastCopy::ReqBuf::bufSize' [-Wmissing-field-initializers]
../RapidCopy/fastcopy.cpp:1840:28: warning: missing initializer for member 'FastCopy::ReqBuf::reqSize' [-Wmissing-field-initializers]
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::FlushMoveList(bool)':
../RapidCopy/fastcopy.cpp:2013:17: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
                 && (!isSameDrv || is_nextexit)) {
                 ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::GetDirExtData(FastCopy::ReqBuf*, FileStat*)':
../RapidCopy/fastcopy.cpp:2063:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                     == SYSCALL_ERR) {
                     ^
In file included from /usr/include/dirent.h:244:0,
                 from ../RapidCopy/fastcopy.cpp:16:
../RapidCopy/fastcopy.cpp:2270:54: warning: invalid access to non-static data member 'FastCopy::ReqHeader::stat'  of NULL object [-Winvalid-offsetof]
         if ((ret = PrepareReqBuf(offsetof(ReqHeader, stat) + stat->minSize, size, stat->fileID,
                                                      ^
../RapidCopy/fastcopy.cpp:2270:54: warning: (perhaps the 'offsetof' macro was used incorrectly) [-Winvalid-offsetof]
../RapidCopy/fastcopy.cpp: At global scope:
../RapidCopy/fastcopy.cpp:2878:55: warning: unused parameter 'src_len' [-Wunused-parameter]
 BOOL FastCopy::OpenFileBackupProc(FileStat *stat, int src_len)
                                                       ^
../RapidCopy/fastcopy.cpp:2905:69: warning: unused parameter 'in_len' [-Wunused-parameter]
 BOOL FastCopy::OpenFileBackupAclLocal(FileStat *stat,VBuf *buf,int *in_len){
                                                                     ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::ReadFileWithReduce(int, void*, long unsigned int, long unsigned int*, void*)':
../RapidCopy/fastcopy.cpp:3214:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if(transed == SYSCALL_ERR){
                    ^
../RapidCopy/fastcopy.cpp:3154:19: warning: unused variable 'list' [-Wunused-variable]
     struct aiocb *list[aio_pnum];  //実験用
                   ^
../RapidCopy/fastcopy.cpp: At global scope:
../RapidCopy/fastcopy.cpp:3146:89: warning: unused parameter 'overwrap' [-Wunused-parameter]
 BOOL FastCopy::ReadFileWithReduce(int hFile, void *buf, DWORD size, DWORD *reads, void *overwrap)
                                                                                         ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::ReadFileXattrWithReduce(int, char*, void*, long unsigned int, long unsigned int*, off_t, qint64)':
../RapidCopy/fastcopy.cpp:3293:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(size > remain_size){
             ^
In file included from /usr/include/dirent.h:244:0,
                 from ../RapidCopy/fastcopy.cpp:16:
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::ReadFileProc(int, int*, int)':
../RapidCopy/fastcopy.cpp:3388:47: warning: invalid access to non-static data member 'FastCopy::ReqHeader::stat'  of NULL object [-Winvalid-offsetof]
         if (PrepareReqBuf(offsetof(ReqHeader, stat) + stat->minSize, stat->repSize,
                                               ^
../RapidCopy/fastcopy.cpp:3388:47: warning: (perhaps the 'offsetof' macro was used incorrectly) [-Winvalid-offsetof]
../RapidCopy/fastcopy.cpp:3413:62: warning: invalid access to non-static data member 'FastCopy::ReqHeader::stat'  of NULL object [-Winvalid-offsetof]
                 if ((ret = PrepareReqBuf(offsetof(ReqHeader, stat) +
                                                              ^
../RapidCopy/fastcopy.cpp:3413:62: warning: (perhaps the 'offsetof' macro was used incorrectly) [-Winvalid-offsetof]
../RapidCopy/fastcopy.cpp:3452:76: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (!ret || trans_size != (DWORD)req_buf.bufSize && trans_size < remain_size) {
                                                                            ^
../RapidCopy/fastcopy.cpp:3452:62: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
             if (!ret || trans_size != (DWORD)req_buf.bufSize && trans_size < remain_size) {
                                                              ^
../RapidCopy/fastcopy.cpp:3456:30: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
                 if(is_stream && !(info.flags & REPORT_STREAM_ERROR)
                              ^
../RapidCopy/fastcopy.cpp:3474:69: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (!isSameDrv && info.mode == MOVE_MODE && remain_size > trans_size) {
                                                                     ^
../RapidCopy/fastcopy.cpp:3481:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (waitTick && remain_size > trans_size) Wait();
                                         ^
In file included from /usr/include/dirent.h:244:0,
                 from ../RapidCopy/fastcopy.cpp:16:
../RapidCopy/fastcopy.cpp:3492:62: warning: invalid access to non-static data member 'FastCopy::ReqHeader::stat'  of NULL object [-Winvalid-offsetof]
             if ((ext_ret = PrepareReqBuf(offsetof(ReqHeader, stat) + stat->minSize,
                                                              ^
../RapidCopy/fastcopy.cpp:3492:62: warning: (perhaps the 'offsetof' macro was used incorrectly) [-Winvalid-offsetof]
../RapidCopy/fastcopy.cpp:3499:62: warning: invalid access to non-static data member 'FastCopy::ReqHeader::stat'  of NULL object [-Winvalid-offsetof]
             if ((ext_ret = PrepareReqBuf(offsetof(ReqHeader, stat) + stat->minSize,
                                                              ^
../RapidCopy/fastcopy.cpp:3499:62: warning: (perhaps the 'offsetof' macro was used incorrectly) [-Winvalid-offsetof]
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::CheckDstRequest()':
../RapidCopy/fastcopy.cpp:3552:11: warning: enumeration value 'DSTREQ_NONE' not handled in switch [-Wswitch]
     switch(dstAsyncRequest) {
           ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::ReadDstStat()':
../RapidCopy/fastcopy.cpp:3631:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (dstStatIdxBuf.RemainSize() <= sizeof(FileStat *)
                                            ^
../RapidCopy/fastcopy.cpp:3639:67: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         else if((strlen((char*)confirmDst) - strlen(wk_filename)) == dstBaseLen && isExtendDir){
                                                                   ^
../RapidCopy/fastcopy.cpp:3652:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (dstStatIdxBuf.RemainSize() <= sizeof(FileStat *)
                                            ^
../RapidCopy/fastcopy.cpp:3731:44: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (dstStatIdxBuf.RemainSize() <= sizeof(FileStat *)
                                            ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::DeleteDirProc(void*, int, void*, FileStat*, bool)':
../RapidCopy/fastcopy.cpp:3987:96: warning: statement has no effect [-Wunused-value]
     int  new_dir_len = dir_len + sprintfV(MakeAddr(path, dir_len), FMT_CAT_ASTER_V, fname); -1 ;
                                                                                                ^
../RapidCopy/fastcopy.cpp: In member function 'void FastCopy::GenRandomName(void*, int, int)':
../RapidCopy/fastcopy.cpp:4195:30: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
     static char *char_dict = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
                              ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::WriteRandomData(void*, FileStat*, bool)':
../RapidCopy/fastcopy.cpp:4237:11: warning: unused variable 'flg' [-Wunused-variable]
     DWORD flg = (is_nonbuf ? F_NOCACHE : 0);
           ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::CheckAndCreateDestDir(int)':
../RapidCopy/fastcopy.cpp:4341:60: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
         if (isListingOnly || !mkdir((const char*)dst,0777) && isListing) {
                                                            ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::WriteProc(int)':
../RapidCopy/fastcopy.cpp:4490:52: warning: narrowing conversion of '(((int)((FastCopy*)this)->FastCopy::writeReq->FastCopy::ReqHeader::command) + 48)' from 'int' to 'char' inside { } [-Wnarrowing]
                 WCHAR cmd[2] = { writeReq->command + '0', 0 };
                                                    ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::WriteDirProc(int)':
../RapidCopy/fastcopy.cpp:4584:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if(mkdirQueueBuf.RemainSize() < sizeof(int)
                                           ^
../RapidCopy/fastcopy.cpp:4533:17: warning: unused variable 'dststat' [-Wunused-variable]
     struct stat dststat;
                 ^
../RapidCopy/fastcopy.cpp:4534:11: warning: unused variable 'rc' [-Wunused-variable]
     int   rc = 0;
           ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::MakeDigestAsync(FastCopy::DigestObj*)':
../RapidCopy/fastcopy.cpp:5108:36: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
             if (isAbort || io_size && (!ReadFileWithReduce(hFile, calc->data, io_size,
                                    ^
../RapidCopy/fastcopy.cpp: At global scope:
../RapidCopy/fastcopy.cpp:5176:65: warning: unused parameter 'share' [-Wunused-parameter]
 int FastCopy::CreateFileWithRetry(void *path, DWORD mode, DWORD share,
                                                                 ^
../RapidCopy/fastcopy.cpp:5177:9: warning: unused parameter 'sa' [-Wunused-parameter]
     int sa, DWORD cr_mode, DWORD flg, void* hTempl, int retry_max)
         ^
../RapidCopy/fastcopy.cpp:5177:19: warning: unused parameter 'cr_mode' [-Wunused-parameter]
     int sa, DWORD cr_mode, DWORD flg, void* hTempl, int retry_max)
                   ^
../RapidCopy/fastcopy.cpp:5177:45: warning: unused parameter 'hTempl' [-Wunused-parameter]
     int sa, DWORD cr_mode, DWORD flg, void* hTempl, int retry_max)
                                             ^
../RapidCopy/fastcopy.cpp:5177:57: warning: unused parameter 'retry_max' [-Wunused-parameter]
     int sa, DWORD cr_mode, DWORD flg, void* hTempl, int retry_max)
                                                         ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::WriteFileWithReduce(int, void*, long unsigned int, long unsigned int*, void*)':
../RapidCopy/fastcopy.cpp:5260:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if(transed == SYSCALL_ERR){
                    ^
../RapidCopy/fastcopy.cpp:5197:11: warning: unused variable 'maxWriteSizeSv' [-Wunused-variable]
     DWORD maxWriteSizeSv = maxWriteSize;
           ^
../RapidCopy/fastcopy.cpp:5201:19: warning: unused variable 'list' [-Wunused-variable]
     struct aiocb *list[aio_pnum];  //aio実験用
                   ^
../RapidCopy/fastcopy.cpp: At global scope:
../RapidCopy/fastcopy.cpp:5193:91: warning: unused parameter 'overwrap' [-Wunused-parameter]
 BOOL FastCopy::WriteFileWithReduce(int hFile, void *buf, DWORD size, DWORD *written,void* overwrap)
                                                                                           ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::WriteFileXattrWithReduce(int, char*, void*, long unsigned int, long unsigned int*, void*, qint64, qint64)':
../RapidCopy/fastcopy.cpp:5298:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(((file_size - remain_size) + *written) == file_size){
                                               ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::WriteFileProc(int, int)':
../RapidCopy/fastcopy.cpp:5479:30: error: 'FALLOC_FL_ZERO_RANGE' was not declared in this scope
                 fallocate(fh,FALLOC_FL_ZERO_RANGE,0,file_size);
                              ^
../RapidCopy/fastcopy.cpp:5560:60: warning: narrowing conversion of '(((int)((FastCopy*)this)->FastCopy::writeReq->FastCopy::ReqHeader::command) + 48)' from 'int' to 'char' inside { } [-Wnarrowing]
                         WCHAR cmd[2] = { writeReq->command + '0', 0 };
                                                            ^
../RapidCopy/fastcopy.cpp:5721:37: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
     if ((isListingOnly || isListing && !is_digest) && !is_stream && ret) {
                                     ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::WriteFileBackupProc(int, int)':
../RapidCopy/fastcopy.cpp:5743:52: warning: narrowing conversion of '(((int)((FastCopy*)this)->FastCopy::writeReq->FastCopy::ReqHeader::command) + 48)' from 'int' to 'char' inside { } [-Wnarrowing]
                 WCHAR cmd[2] = { writeReq->command + '0', 0 };
                                                    ^
../RapidCopy/fastcopy.cpp:5769:52: warning: narrowing conversion of '(((int)((FastCopy*)this)->FastCopy::writeReq->FastCopy::ReqHeader::command) + 48)' from 'int' to 'char' inside { } [-Wnarrowing]
                 WCHAR cmd[2] = { writeReq->command + '0', 0 };
                                                    ^
../RapidCopy/fastcopy.cpp: At global scope:
../RapidCopy/fastcopy.cpp:5735:48: warning: unused parameter 'dst_len' [-Wunused-parameter]
 BOOL FastCopy::WriteFileBackupProc(int fh, int dst_len)
                                                ^
../RapidCopy/fastcopy.cpp:5826:43: warning: unused parameter 'is_finish' [-Wunused-parameter]
 BOOL FastCopy::ChangeToWriteModeCore(BOOL is_finish)
                                           ^
In file included from /usr/include/dirent.h:244:0,
                 from ../RapidCopy/fastcopy.cpp:16:
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::SendRequest(FastCopy::Command, FastCopy::ReqBuf*, FileStat*)':
../RapidCopy/fastcopy.cpp:6004:47: warning: invalid access to non-static data member 'FastCopy::ReqHeader::stat'  of NULL object [-Winvalid-offsetof]
         ret = AllocReqBuf(offsetof(ReqHeader, stat) + (stat ? stat->minSize : 0), 0, buf);
                                               ^
../RapidCopy/fastcopy.cpp:6004:47: warning: (perhaps the 'offsetof' macro was used incorrectly) [-Winvalid-offsetof]
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::RecvRequest()':
../RapidCopy/fastcopy.cpp:6052:50: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
             || (info.flags & SERIAL_VERIFY_MOVE) && digestList.Num() > 0) {
                                                  ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::SetFinishFileID(qint64, FastCopy::MoveObj::Status)':
../RapidCopy/fastcopy.cpp:6093:54: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
         while (moveFinPtr = moveList.Fetch(moveFinPtr)) {
                                                      ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::End()':
../RapidCopy/fastcopy.cpp:6186:15: warning: deleting 'void*' is undefined
     delete [] hardLinkDst;
               ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::Suspend()':
../RapidCopy/fastcopy.cpp:6197:24: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
     if (!hReadThread_c && !hWriteThread_c || isSuspend){
                        ^
../RapidCopy/fastcopy.cpp: In member function 'bool FastCopy::Resume()':
../RapidCopy/fastcopy.cpp:6227:24: warning: suggest parentheses around '&&' within '||' [-Wparentheses]
     if (!hReadThread_c && !hWriteThread_c || !isSuspend){
                        ^
../RapidCopy/fastcopy.cpp: At global scope:
../RapidCopy/fastcopy.cpp:6287:35: warning: unused parameter 'signum' [-Wunused-parameter]
 void FastCopy::signal_handler(int signum){
                                   ^
../RapidCopy/fastcopy.cpp: In member function 'FastCopy::Confirm::Result FastCopy::ConfirmErr(const char*, const void*, long unsigned int, const char*, char*)':
../RapidCopy/fastcopy.cpp:6525:11: warning: enumeration value 'CONTINUE_RESULT' not handled in switch [-Wswitch]
     switch(confirm.result){
           ^
../RapidCopy/fastcopy.cpp: At global scope:
../RapidCopy/fastcopy.cpp:1:14: warning: 'fastcopy_id' defined but not used [-Wunused-variable]
 ﻿static char *fastcopy_id =
              ^
Makefile:3031: recipe for target 'fastcopy.o' failed
make: *** [fastcopy.o] Error 1
22:42:27: プロセス "/usr/bin/make" はコード 2 で終了しました。
プロジェクト rapidcopy_main のビルド・デプロイ中にエラーが発生しました (キット Desktop Qt 5.6.2 GCC 64bit)

**Comment by KengoSawa2** [comment]
コンパイルエラー報告ありがとうございます。

現象ですが、CentOS7でのコンパイル時ということでいいでしょうか？

書き込み時の断片化抑止を改善したのですが、CentOS7でのコンパイル確認忘れてました。
masterブランチを本日修正してみたので、再度お試しください。

なお、CentOS7向けコンパイルの場合は
https://github.com/KengoSawa2/RapidCopy/blob/master/rapidcopy_main.pro
上記ファイル中の

> #CONFIG += CentOS7
上記のconfigを有効にして(#を外して)コンパイルしてください。
Ubuntuの場合は特に何もする必要はありません。
