### ISSUE TITLE
Precompiled portable executable?

### ISSUE THREAD

**Issue by gslager** [KengoSawa2/RapidCopy#9]
Hi,
I use Fastcopy on Windows and would like to use RapidCopy on a new Ubuntu installation. Unfortunately, I'm not a programmer so compiling my own version is above my pay grade :)
Wondering if you could post an executable version that could simply be downloaded and ran on Ubuntu?
Thanks.

**Comment by KengoSawa2** [comment]
You can download static binary:)
But, now only Ubuntu 16.04 and 18.04.

[https://github.com/KengoSawa2/RapidCopy/tree/master/static_bin](https://github.com/KengoSawa2/RapidCopy/tree/master/static_bin)
